### ISSUE TITLE
Release date of the new dataset

### ISSUE THREAD

**Issue by homothetic** [dongkwonjin/RVLD#1]
Great work on your project! I want to know when you plan to release the new dataset "OpenLane-V".

**Comment by luweiqing** [comment]
I want to know how to build the new dataset from "OpenLane" to "OpenLane-V" or  can you release  "OpenLane-V" straightly for downloading? Thank you for your great work!

**Comment by dongkwonjin** [comment]
Thank you for your attention! It will be uploaded within two weeks. I will contact you again when uploaded.

**Comment by dongkwonjin** [comment]
We uploaded : )
