### ISSUE TITLE
how to build the new dataset "OpenLane-V"

### ISSUE THREAD

**Issue by luweiqing** [dongkwonjin/RVLD#2]

**Comment by luweiqing** [comment]
I read your paper,it is a great job,and  I have a question for the new dataset:  can you provide a download for "OpenLane"  and  then tell me how to build the new dataset "OpenLane-V" from "OpenLane",  or  provide straightly the download for "OpenLane-V"?

**Comment by dongkwonjin** [comment]
We uploaded!
