### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by CZY-Code** [dongkwonjin/RVLD#7]
Thanks for your contribution on new dataset. 
But i have a question:
The label folder /OpenLane-V/label/training/ contains 450 clips, each containing a maximum of 199 images and a minimum of 5 images, 
But the file /OpenLane-V/list/datalist_video_training.pickle contain 622 clips, each containing a maximum of 199 images and a minimum of 1 images. And both folders contain the same total of 68143 images.
Why split 450 clips into 622？

**Comment by dongkwonjin** [comment]
We are sorry for the late reply.

We split them because some clips are not consecutive in the same video. Sorry for such confusion. Testing on 622 clips is correct.

Thank you for your attention.

**Comment by Yzichen** [comment]
I've noticed that the video gets split when the vehicle changes lanes, which doesn't seem to make much sense .
